name: Build and Deploy
on:
    push:
        branches: [ main ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    persist-credentials: false
            -   name: Setup node
                uses: actions/setup-node@v4
                with:
                    node-version: 20
            -   name: Setup pnpm
                uses: pnpm/action-setup@v4
                id: pnpm-install
                with:
                    run_install: false
            -   name: Build
                run: |
                    node -v
                    npm -v
                    pnpm -v
                    node scripts/init.mjs
                    node scripts/build.mjs github
            -   name: Deploy
                uses: JamesIves/github-pages-deploy-action@v4
                with:
                    token: ${{ secrets.ACCESS_TOKEN }}
                    branch: gh-pages
                    folder: dist
                    force: true
