packages:
  - apps/*
  - packages/*

minimumReleaseAge: 0

allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': true
  better-sqlite3: true
  core-js: true
  easy-day-js: true
  es5-ext: true
  esbuild: true
  msgpackr-extract: true
  sharp: true
  unrs-resolver: true
  workerd: true
