import { Menu } from '@commons/core/utils/menu';

export const appSiderMenus: Menu[] = [
    {
        key: 'workbench',
        title: '工作台',
        label: 'common.label_workbench',
        icon: 'mdi:view-dashboard-outline',
        authorities: ['workbench'],
        enabled: true,
        path: '/workbench',
    },
    {
        key: 'dashboard',
        title: '仪表盘',
        label: 'common.label_dashboard',
        icon: 'mdi:view-dashboard-outline',
        authorities: ['dashboard'],
        enabled: true,
        path: '/dashboard',
    },
    {
        key: 'site',
        title: '站点管理',
        label: 'common.site_management',
        icon: 'mdi:apps',
        authorities: ['site'],
        enabled: true,
        items: [
            {
                key: 'announcement',
                title: '资讯管理',
                label: 'common.announcement_management',
                icon: 'mdi:bullhorn-outline',
                authorities: ['site:announcement'],
                enabled: true,
                path: '/announcement/index',
            },
            {
                key: 'product',
                title: '产品管理',
                label: 'common.product_management',
                icon: 'mdi:map-outline',
                authorities: ['site:product'],
                enabled: true,
                path: '/product/index',
            },
        ],
    },
    {
        key: 'resource',
        title: '资源管理',
        icon: 'mdi:apps',
        authorities: ['resource'],
        enabled: true,
        items: [
            {
                key: 'dict',
                title: '字典管理',
                icon: 'mdi:apps',
                authorities: ['resource:dictionary'],
                enabled: true,
                path: '/dictionary/index',
            },
            {
                key: 'attachment',
                title: '附件管理',
                icon: 'mdi:apps',
                authorities: ['resource:attachment'],
                enabled: true,
                path: '/attachment/index',
            },
        ],
    },
    {
        key: 'organization',
        label: 'common.organization_management',
        title: '组织架构',
        icon: 'mdi:account-group-outline',
        authorities: ['organization'],
        enabled: true,
        items: [
            {
                key: 'user',
                label: 'common.user_management',
                title: '用户管理',
                icon: 'mdi:account-group-outline',
                authorities: ['organization:user'],
                enabled: true,
                path: '/user/index',
            },
        ],
    },
    {
        key: 'system',
        title: '系统设置',
        icon: 'mdi:cog-outline',
        authorities: ['system'],
        enabled: true,
        items: [
            {
                key: 'authority',
                title: '权限管理',
                icon: 'mdi:cog-outline',
                authorities: ['system:authority'],
                enabled: true,
                path: '/authority/index',
            },
            {
                key: 'role',
                title: '角色管理',
                icon: 'mdi:cog-outline',
                authorities: ['system:role'],
                enabled: true,
                path: '/role/index',
            },
            {
                key: 'setting',
                title: '系统设置',
                icon: 'mdi:cog-outline',
                authorities: ['system:setting'],
                enabled: true,
                path: '/system-settings/index',
            },
            {
                key: 'user-session',
                title: '在线用户管理',
                icon: 'mdi:cog-outline',
                authorities: ['system:user'],
                enabled: true,
                path: '/user-session/index',
            },
            {
                key: 'logging',
                title: '日志管理',
                icon: 'mdi:cog-outline',
                authorities: ['system:logging'],
                enabled: true,
                path: '/logging/index',
            },
        ],
    },
];

export const userCenterMenus: Menu[] = [
    {
        key: 'user-center',
        title: '用户中心',
        icon: 'mdi:shield-account-outline',
        enabled: true,
        path: '/user-center/index',
    },
    {
        key: 'user-notice',
        title: '消息',
        icon: 'mdi:message-outline',
        enabled: true,
        path: '/user-center/notice',
    },
    {
        key: 'user-profile',
        title: '个人资料',
        icon: 'mdi:information-outline',
        enabled: true,
        path: '/user-center/account',
    },
    {
        key: 'user-password',
        title: '修改密码',
        icon: 'mdi:lock-outline',
        enabled: true,
        path: '/user-center/password',
    },
];
